### ISSUE TITLE
Setup CSRF Protection

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#144]
### Description

Since we are using cookie authentication, we need to add CSRF protection.

 

### Additional Information

Need access to the common CSRF Certificate

See how this is done in the Apps.

### Tasks

- [x] Set up CSRF Protection in backend
- [x] Setup CSRF 

### Acceptance Criteria
- [ ] All post operations supporting JWTCookie need to be protected by CSRF protection

**Comment by acn-dgopa** [comment]
@TheTechArch I was just wondering if we must enable csrf protection for some **GET** operations as well F.ex when fetching a refreshed token, retreiving delegation/rights information that exposes a personal number?

**Comment by TheTechArch** [comment]
My understanding post is enough. This is what we have in apps.
