### ISSUE TITLE
Add support for deleting resources from resourceregistry

### ISSUE THREAD

**Issue by Sondre-B** [Altinn/altinn-access-management#150]
### Description

Add support for deleting resources from resourceregistry by passing resourceregistryId

### Acceptance Criterias

Given the existing DeleteRules-endpoint only allowing deleting rules based on org/app (AltinnAppId).
When the rule is based on a resource from resourceregistry, there will be no org/app.
Then it should be made possible to delete rule based on resourceregistryId as well as the existing org/app functionality.

**Comment by jonkjetiloye** [comment]
Internal implementation of revoke. Testing will be covered by separate issues for API revoke-endpoints
