### ISSUE TITLE
Define detailed process for migration of maskinporten scope resources and delegations

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#162]
### Description

We need to create a detailed process for how to migrate to new solution in Altinn 3

### Additional Information

- [ ] Plan how first resources are migrated
- [ ] Describe how we are gonna verify the content created. 
- [ ] Describe the migration process of delegations
- [ ] Describe how we are counting and verifying the delegations
- [ ] Describe how we will prevent usage (if any) during periode
- [ ] Describe what kind feature toggles we need (enable link to new solution, disable delegation of old)
- [ ] Describe and create possible scripts to disable delegation of these resources in Altinn 2

**Comment by sivaglen** [comment]
Denne er utdatert. lukkes.
