### ISSUE TITLE
Backend for Frontend API strategy

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#251]
### Intro

The current approach for API used by the front end is to use the same API that is planned to be used for external consumption by end-user systems or agency systems. 

We follow an API First approach where API design focuses on good generic APIs that others can consume and understand.

**Approx 50% of Altinn traffic is direct API calls from external systems. So API needs to follow best practices.**

The API is separated into components for natural areas. The front end is added for components where Altinn needs to expose functionality for end users through the browser. 

- App Template: Shared React Frontend - Uses standard API for end-user and agency systems. Some APIs added to support fronted that will not be used by end-user systems 
- Receipt: React Frontend: Only used by fronted
- Access Management:  React Frontend - Uses standard access management backend API, but Proxy API for other components is added for the frontend.
- Altinn Studio: React frontend - The backend is only used by the frontend. Practically a BFF

For Access Management Frontend and other coming frontends, it can be suboptimal.

- Requires to call multiple APIs to present a view
- Needs to "map" data from multiple views in the browser
- Need to add proxy API in management backend.

We need to decide if we going to continue this strategy or allow for a more frontend-optimized API

### As Is

Pro
-There is only one API implementation. No risk of various responses depending on the endpoint used. This has been a problem in Altinn 2, where we have a separate front and external API. 
- We are dogfooding our API. Make sure that we try to test the API if it makes sense or works as intended. In Altinn 2, this was a problem in the beginning with some nonworking APIs that none consumed. 

Cons
- Needs to make additional calls or complex mapping of data that is not optimized for views/GUI
- Needs to add a proxy for other components that need to be consumed by the front end.

![image](https://user-images.githubusercontent.com/13309071/214069264-bc6f3b5d-aaa9-41a3-922c-fd88918cdc81.png)

### BFF API implemented in the component backend

One approach is to add additional API in the current backend that is more targeted for the front end.

Pro
- No need for additional deployments
- Same well-known technology
- Can quickly add new frontend versions of current API

Cons
- Need to  be able to differentiate swagger between generic and BFF API
- Are able to use internal methods that does not match real exposed API

Need to decide
- When are we allowed to create API l like this?

![image](https://user-images.githubusercontent.com/13309071/214069446-29315f4f-ecda-4c73-ac58-050f643b296a.png)

### Separate BFF

This architecture adds a layer of the backend.  All Apis consumed by Frontend needs to come from this new layer. 

Architecture decisions
- Hosting. Where should this BFF be hosted? A new portal.altinn.no cluster? (receipt could be moved there)
- Call pattern. Should only work as proxy?
- Technology. Can teams select any backend technology? 
- Do we need to authenticate in BFF layer? (assumption yes)
- Do we need to authorize in BFF layer? (assumption no)
- 

Pro
- Frontend developers can add and modify API without needing to consider other consumers of core backend API
- You can add frontend API that functional belong to any component (example profile, authentication API)
- You can in based BFF on any technology
- No need to update API management (depending on hosting)

Con
- Additional latency for some APIs
- Deployment complexity (separate Kubernetes Cluster? Additional component to deploy)
- Development complexity. Dependence on additional layers. Same API needs to be implemented in multiple components

#### Technology

With a separate BFF you can based it on different technology than the core backend components.

Some options

##### .Net 

Pro 
- Known technology. 
- Can reuse code and models from core components
- Can reuse code like token generation
- High performance

##### Node (Typescript/javascript)
- FE developers without back end knowledge more familier with technology

##### Go

https://docs.altinn.studio/technology/architecture/components/application/construction/altinn-platform/authorization/authorizationbff.drawio.svg

#### Decided
1.  Frontend for Altinn Platform components can establish a BFF layer to support the SPA frontend. 
2. The BFF layer will expose proxies for all APIs consumed by the  SPA.  Calling direct to the original API will cause dependencies
3. The team can decide on technology from the list of approved technologies to use
4. Authentication is performed in BFF
5. Authorization is not performed in BFF
6. Frontend files (index.html, javascript, SVG, CSS +++) is hosted in BFF.

#### Still open

7. Deployment
We have the following possibilities.
- Separate BFF/frontend Kubernetes cluster  (portal.altinn.no) with mapping to the various apps /accessmanagement  /profile /messagebox +++
- Separate area cluster  (accessmanagement.altinn.no)
- Azure Container apps with a separate domain accessmanagement.altinn.no

8. BFF technology
We are allowed to use .Net as BFF. Node and other technologies need to be approved before use.

**Comment by sivaglen** [comment]
Kan vi lukke denne issuen nå @TheTechArch ?
