### ISSUE TITLE
Altinn 2 panel redirect 

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-access-management#254]
### Description

1. System Resource
2.  Policy/ regler for ny ressurs
3. Oppdater med lenke til Altinn 2. 
4. Dekativer mulighet for visning av rettighetr
5. Slette delegeringer på testpunkt. Lage slettescript
6.

**Comment by sivaglen** [comment]
@TheTechArch må denne gjøres før vi går i produksjon med Delegerbare API ressurser? 
Hvis ja, knytt den til milestone "Migrert Delegerbare API...." :)

**Comment by sivaglen** [comment]
Jeg mener denne issue løses med følgende andre issuer: 

- https://github.com/Altinn/altinn-authorization/issues/68
- https://dev.azure.com/digdir/Altinn/_workitems/edit/62926
- https://dev.azure.com/digdir/Altinn/_workitems/edit/62826
- https://dev.azure.com/digdir/Altinn/_workitems/edit/62927

Lukker derfor denne.
