### ISSUE TITLE
Add unit tests for bff

### ISSUE THREAD

**Issue by acn-dgopa** [Altinn/altinn-access-management#300]
### Description

Unit tests to be added to the  access management bff

### Tasks

- [ ] Add unit test project to the bff project

### Acceptance Criterias

- It should be possible to fetch inbound/outbound delegations by sending a party id
- It should be possible to fetch inbound/outbound delegations by sending party as "organization" and header "party-organizationumber"
- The inbound/outbound delegations msut be returned with resource information returned in user's preferred language

**Comment by sivaglen** [comment]
@acn-dgopa - kan denne lukkes?

**Comment by acn-dgopa** [comment]
ja :) @sivaglen
