### ISSUE TITLE
IdentityTelemetryFilter has wrong in url check

### ISSUE THREAD

**Issue by lovoll** [Altinn/altinn-access-management#313]
### Description of the bug

The IdentityTelemetryFilter in AccessManagment project looks like it is a copy paste of the version in Authorization without cange to the url check defined to only process if the requst has a url that contains "authorization/api/" this should probably been updated to be "accessmanagement/api/"

### Steps To Reproduce

access any api in accessmanagment

The telemetry will not add Properties to the request for userid, authlevel, partyid and organisastionnumber.

**Comment by sivaglen** [comment]
@lovoll kan denne lukkes?
