### ISSUE TITLE
Duplicate Delegations.js K6 tests for access-management endpoint for Delegations API

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#319]
### Description

The K6 tests testing the authorization/api/v1/Delegations/ API should be duplicated to execute the same tests for changes in access-management repo for the same APIs under accessmanagement/api/v1/Delegations/

### Tasks

- [ ] Duplicate K6 tests with different configured endpoint
- [ ] Setup pipeline triggering the tests on PR for access-management repo

**Comment by sivaglen** [comment]
Dette har antagelig lite verdi  å gjøre fordi disse endepunktene "dør".
