### ISSUE TITLE
Casing issue with resource type stored in postgres accessmanagement.resource table

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#330]
### Description of the bug

Receiving resource information in access-management from the resource registry stores the ResourceType with microsofts Pascal-casing in stead of lower casing as all other text and enum values in postgres.

This cause the lookup of delegations in the admin (aka serviceowner/maskinporten integration API) to fail

### Steps To Reproduce

1. Create a MaskinportenSchema resource through the ResourceRegistry API (with a scope resource reference)
2. Check the postgre table accessmanagement.resource in for resource update made to access-management

Expected: resourcetype to be: 'maskinportenschema' as all other text/emum values in postgre is processed with lower casing
Actual: resourcetype is 'MaskinportenSchema'

3. Perform Maskinporten Delegation of the MaskinportenSchema created in step 1

> POST `{EnvAccessManagementUrl}}/accessmanagement/api/v1/:party/delegations/maskinportenschema/`

4. Get Maskinporten Delegations from API for serviceowner/maskinporten integration 

> GET `{{EnvAccessManagementUrl}}/accessmanagement/api/v1/admin/delegations/maskinportenschema?supplierOrg={{supplierOrg}}&consumerOrg={{consumerOrg}}&Scope={{Scope}}`

Expected: delegation from step 3. as result
Actual: Empty result

### Additional Information

Suggested fix:
1. Even if stored as just a string in the accessmanagement.resource table, AM needs to use it's ResourceType Enum on the input Model. This will cause migration of new resource types to fail without a code update in AM as well, but this is a better solution than receiving data that will cause runtime exception in AM if read from the DB at a later point.
2. The Enum must be updated with attributes to force lower case serialization when stored as string in the database.
3. a DB script must be executed to convert all existing resource types in accessmanagement.resource to lower case in AT environments.

**Comment by acn-dgopa** [comment]
A temporary fix of removing casing conversion is merged. https://github.com/Altinn/altinn-access-management/pull/348

**Comment by acn-dgopa** [comment]
We go with the solution 1 where ResourceType in AM model will be an enum instead of string.

**Comment by jonkjetiloye** [comment]
Old technical issue with integration between resource registry and accessmanagement. Solved and verified through delegationscheme migration test runs in both AT and TT. Closing issue
