### ISSUE TITLE
Klargjøre Autorisasjon i Altinn 3 for migrering av formidlingstjeneste

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-access-management#344]
# Overordnet beskrivelse 
Formidlingstjenester benytter Autorisasjon som løsning for tilgangsstyring
Autorisasjon skal sørge for tilgangsstyring og kontroll for alle disse også i Altinn 3

# Overordnet beskrivelse av løsning
Arbeid for å migrere selve flyttingen av formidlingstjenesten følges opp her: https://github.com/Altinn/altinn-broker/issues/8

- Ny ressurstype
- Antar at man erstatter bruk av SRR med maskinport-tilgangsstyring
- Antar at det ikke er noe spesielle regler rundt delegering vi må ta høyde for
- Må vurdere om det skal være egne API for delegering/tilgangsstyring
```[tasklist]
### Tasks
```

**Comment by annerisbakk** [comment]
Lukkes - duplikat av https://github.com/Altinn/altinn-authentication/issues/475
