### ISSUE TITLE
Klargjøre Autorisasjon Altinn 3 for migrering av meldingstjenester

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-access-management#345]
# Overordnet beskrivelse
Alle tjenestetyper skal flyttes fra Altinn 2 til Altinn 3 innen juni 2025 (eller slås av/flyttes et annet sted) 
Autorisasjon skal sørge for tilgangsstyring og kontroll for alle disse også i Altinn 3
Dette arbeidet henger antagelig sammen med utredning som gjøres av Team Tilgangsinformasjon (https://github.com/Altinn/altinn-authentication/issues/219) i forbindelse med [dialogporen](https://digdir.github.io/dialogporten/)
Arbeidet må utføres «i fart»: 
- Skal støtte at noen tjenester fortsatt ligger igjen i Altinn2 mens andre er flyttet. 
- Bruker skal ikke merke at vi flytter autorisasjonsløsningen

Denne vil antagelig løses som en del av [Tilby autorisasjon for Dialogporten](https://github.com/Altinn/altinn-access-management/issues/346) 

# Overordnet beskrivelse av løsning
# Spørsmål

**Comment by annerisbakk** [comment]
Avventes ift evt behov fra Melding og Formidling

**Comment by annerisbakk** [comment]
Lukkes etter avtale med Melding og Formidling
