### ISSUE TITLE
Tilby støtte for arbeidsflyt i 3.0 app som krever paralellsignering

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-access-management#349]
# Overordnet beskrivelse 
Parallellsignering refererer til prosessen med å signere et dokument eller en avtale med to eller flere signaturer samtidig. Denne funksjonaliteten brukes når flere personer må signere et dokument, for eksempel i en organisasjon eller bedrift der flere personer er involvert i å signere på en forsendelse.  

# Mer detaljer om behovet
Parallellsignering kan bidra til å fremskynde signeringstiden og redusere ventetiden for alle involverte parter.
Det skal være valgfritt hvilken rekkefølge de ulike signerer i
Det finnes i dag to varianter av paralellsignering i Altinn: 
- hvem som må signeres kalkuleres fra informasjon som legges inn i skjema, f eks når man oppgir ett nytt styre hvor alle styremeldlemmer må signere meldingen
- hvem som må signere oppgis av utfyller som siste steg i utfyllingsprosessen. 

## Kort beskrivelse av løsning: 
- Løsningen støtter allerede signering av flere i en sekvensiell rekkefølge

- Design av workflow og hvordan det skal modelleres i en policy "i app-instansen"
- Ressurspolicy vil inneholde regler "frem til" paralellsteget
- Paralell-operasjonen vil ha en egen policy for hver instans - eller ???
- App må kunne kalle til autorisasjon for at man skal kunne registrere at følgende subject skal kunne utføre følgende action
- Man skal ikke kunne trekke en delegering av instanser for paralellsignering
- GUI i skjema som støtter arbeidsflyt (dette må bakes inn i app-template?)

**Comment by rtafj** [comment]
Dette håndteres av Team Apps, basert på instansdelegering-API, https://github.com/Altinn/altinn-authorization/issues/10
