### ISSUE TITLE
get maskinportenschema returns 500 error when party is "abc"

### ISSUE THREAD

**Issue by ivartryti** [Altinn/altinn-access-management#361]
The following request leads to a 500 error:
https://platform.at23.altinn.cloud/accessmanagement/api/v1/abc/delegations/maskinportenschema/offered

**Comment by lovoll** [comment]
After researching this we found that the error origins in PEP before the controller is invoked so we have only three posible exits
1. context.Fail() ending in a 401 Unauthorized and no info why
2. context,Success() ending in executing the controller
3. Throw an Exeption ending in 500 Server error

So to make it easier to see why you are not authorized we will keep the throwing exception as this will give the user more info getting Invalid party: abc. This is even more as we have two keywords: organization and person so to give feedback to a integrater writing organisation insted of organization we will keep the current handling.

**Comment by lovoll** [comment]
We did keep the original error to be able to get some info on why you are not authorized so closed with won@t fix
