### ISSUE TITLE
Test hele feature - API delegering

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#370]
### **Description**
This is a test issue created to test the whole functionality of API delegering implemented in A3

### **Test cases to be covered**
Test cases to be tested should be listed here. Test cases should cover component level testing and full flow testing. Both positive and negative tests should be listed

**Searching for organizations functionality**
- [x] Search for organization and add it in list
- [x] Search for organization with 8 digit/ 10 digit, click search and see verify error message
- [x] Search with organization with some alphabet, click search and see verify error message
- [x] Add multiple organizations in receivers list
- [x] Delete organizations added to the list

**Searching API to give access functionality**
- [x] Search for keywords in search field and verify API results
- [x] Search for keywords that doesn't match any results
- [x] Filter API  based on provider and verify if all API which belongs to the provider is listed
- [x] Filter API based on multiple providers
- [x] Use both keyword search and provider filter and narrow down search results
- [x] Verify details displayed for an API when you expand and collapse 
- [x] Add APIs to the list to be delegated
- [x] Delete APIs from the list

**Verify delegation confirmation page**
- [x] Verify organization selected appears correctly in confirmation page
- [x] Verify all APIs selected appears correctly in confirmation page
- [x] Verify deletion of API selected in confirmation page
- [x] Verify clicking on Forrige button and going back to previous pages to add organizations/ APIs

**Delegate new API functionality**
- [x] Delegate API to organization and verify if it appears in delegations overview page, also verify if it appears under 'Mottatte API tilganger' for coveredBy
- [x] Delegate multiple APIs to organization and verify if it appears in delegations overview page, also verify if it appears under 'Mottatte API tilganger' for coveredBy
- [x] Delegate APIs to multiple organizations and verify if it appears in delegations overview page, also verify if it appears under 'Mottatte API tilganger' for coveredBy

**Delegations overview page for offeredBy**
- [x] Click on Expand/ collapse arrow for organization and verify if all APIs delegated is listed
- [x] Rediger tilgang - Delete API delegated from delegations overview page. Verify it is not listed in delegations overview page anymore. Verify it is not listed under 'Mottatte API tilganger' for coveredBy
- [x] Rediger tilgang - Delete coveredBy organization from delegations overview page. Verify organization and delegations are not listed in delegations overview page anymore. Verify organization is not listed under 'Mottatte API tilganger' for coveredBy
- [x] Verify list when user has multiple organizations in the list. Expand each organization and verify if scrolling up and down looks fine
- [x] Verify delegations overview page when there are no API delegations, message displayed correctly

**Delegations overview page for coveredBy**
- [x] Click on Expand/ collapse arrow for organization and verify if all APIs received is listed
- [x] Rediger tilgang - Delete API received from delegations overview page. Verify it is not listed in delegations overview page anymore. Verify it is not listed under 'Delegerte API tilganger' for offeredBy
- [x] Rediger tilgang - Delete offeredBy organization from delegations overview page. Verify organization and delegations are not listed in delegations overview page anymore. Verify organization is not listed under 'Delegerte API tilganger' for offeredBy
- [x] Verify list when user has multiple organizations in the list. Expand each organization and verify if scrolling up and down looks fine
- [x] Verify delegations overview page when user has not received any API delegations, message displayed correctly

**Specific tests**
- [x] Verify no error message is shown when an API which is already delegated is selected for delegation
- [x] Verify error message when user doesn't have access to delegate API which requires higher authentication level
- [x] Verify redirection when user is inactive in API delegations page for 30 mins
- [x] Verify error message when user doesn't have access to delegate API.
- [x] For Maskinporten schema created with HADM role requirement, DAGL can delegate API and delete API since DAGL has HADM 
- [x] For Maskinporten schema created with HADM role requirement, HADM can delegate API and delete API
- [x] For Maskinporten schema created with DAGL role requirement, DAGL can delegate API and delete API
- [x] For Maskinporten schema created with DAGL role requirement, person who has got HADM delegated can delegate API and delete API as HADM inherits all roles from DAGL for delegation including DAGL
- [x] For Maskinporten schema created with role requirement APIADMNUF (Programmeringsgrensesnitt for NUF (API)) , person with KNUF (Kontakt person for NUF) role can delegate and delete APIs
- [x] For Maskinporten schema created with role requirement APIADMNUF (Programmeringsgrensesnitt for NUF (API)) , person with  who has got APIADMNUF delegated from KNUF can delegate API and delete API 
- [x] For Maskinporten schema created with role requirement APIADM (Programmeringsgrensesnitt for API) , person with DAGL role can delegate API
- [x] For Maskinporten schema created with role requirement APIADM (Programmeringsgrensesnitt for API) , person with INNH role can delegate API
- [x] For Maskinporten schema created with role requirement APIADM (Programmeringsgrensesnitt for API) , person who has got APIADM delegated from INNH can delegate API and delete API 
- [x] For Maskinporten schema created with role requirement HADM , person who has got APIADM delegated from INNH cannot delegate API since role requirement is HADM
- [x] For Maskinporten schema created with role requirement HADM , person who has got APIADM delegated from INNH can delete API as APIADM is similar to ADMAI in ALtinn2 and gets access to API delegering panel and deletion of APIs
- [x] API delegations done can be fetched via https://at23.altinn.cloud/maskinporten-api/delegations/?scope={scopename}
- [x] Verify it is not possible to delegate APIs using ALtinn2 REST endpoints
- [x] Verify exisitng delegations done for API in Altinn2 does not appear in service owner REST endpoints -   {baseURL}/api/serviceowner/authorization/rights?subject={CoveredBy}&reportee={OfferedBy}&ForceEIAuthentication
- [x] Verify existing delegations done in Altinn2 do not appear in delegations list https://at23.altinn.cloud/api/910438794/authorization/delegations/910434993/rights
- [x] Verify API delegations done in Altinn3 do not appear in delegations list for user https://at23.altinn.cloud/api/910438794/authorization/delegations/910434993/rights
- [x] Verify AppId doesnt appear in rights for org list when org has delegated App https://at23.altinn.cloud/api/910438794/authorization/rights/
- [x] Verify API delegering pages in English language
- [x] Verify API delegering pages in Nynorsk language

**Browser and device testing**
Before starting with this, tester should check with UI/ developer to understand which devices are the important ones to be covered
- [x] Verify complete flow in Chrome
- [x] Verify complete flow in Edge
- [x] Verify complete flow in iPhone
- [x] Verify complete flow in Android

**Comment by anishastphen** [comment]
@jonkjetiloye  can u take a look at the cases documented? please let me know if anything needs to be included

**Comment by jonkjetiloye** [comment]
@anishastphen 

**Feedback:**
>Only user with NUF role can delegate APIs, where MaskinPorten scheme created has NUF set up as role - person should have got NUF delegated from a person with KNUF role

I assume "NUF role" here refers to the new delegable role which KNUF can delegate: `Programmeringsgrensesnitt for NUF (API)`?
Also, I don't see a similar test for the delegable role which DAGL/Styreleder etc. can delegate: `Programmeringsgrensesnitt (API)`

>Verify it is possible to fetch API delegations with Altinn2 service owner REST endpoints - {baseURL}/api/serviceowner/authorization/rights?subject={CoveredBy}&reportee={OfferedBy}&ForceEIAuthentication

The existing/old delegations in Altinn 2 should be hidden if the feature toggle `MaskinportenDelegationsDisableAltinnII` is enabled. I thought this would cover both portal and APIs but I haven't verified this

**Suggestion for additional test scenarios:**

- Revoke/additional delegation to an organization with organization number starting with 0 (known bugs to be solved by https://github.com/Altinn/altinn-access-management-frontend/issues/283)
