### ISSUE TITLE
API delegering - search for organization improvements

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#383]
Noticed few things in API delegering under 'Søk på organisasjonsnummer' field

1. Search shows error message for incorrect organization number when it is exactly a 9 digit number. If user accidently writes 8- digit or 10 digit, it doesn't show any error message
2. When I write an 8-digit number and click on Search icon, it looks irresponsive. Is this how it is supposed to be? Should it show some error message while clicking on Search icon?

**Comment by allinox** [comment]
@anishastphen 
As of now, if you write anything other than 9 digits (and there are no matches in your previously used organisations) then you don'r get an error message, but you do get an information message telling you to input 9 digits.
![image](https://user-images.githubusercontent.com/22012997/229748450-f08cfe5b-2789-4572-8a4a-d91a45c90937.png)


Also, the search icon is just an icon, not really a button so it doesn't actually do anything.. 😅
The search happens dynamically, with every inserted digit.
That said, the fact that you thought it was a button might be an argument for moving the icon to the left side to make it more clear that this isn't a button.

**Comment by Albertlarsen** [comment]
It says in the info panel that you should write the 9 digit org number though

**Comment by jonkjetiloye** [comment]
Refinement:
1. Limit the input to only allow 9 characters
2. Move icon to left side of the input box (must verified and done in design system)

**Comment by Albertlarsen** [comment]
Maybe we can discuss adding validation to SearchField like many other design systems have like [MUI](https://mui.com/material-ui/react-text-field/)?

**Comment by jonkjetiloye** [comment]
Refinement part 2:
- Only move the icon. We'll reevaluate the issue of orgnumber validation if users have issues
