### ISSUE TITLE
API delegering - session time out results in page not found

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#384]
Login to AT23 and move to API deleringering pages 
Let the session be idle for 30 mins
Now if you open the tab where you have the idle session, you see - page cannot be found

![Image](https://user-images.githubusercontent.com/117180726/229765125-75f05756-c695-4351-9b1c-c19141e8e3e3.png)

**Comment by anishastphen** [comment]
@rtafj @jonkjetiloye

**Comment by rtafj** [comment]
@jonkjetiloye  - her burde man vel enten få beskjed om at man er utlogget pga idle time, eller redirectes til startside eller innlogging? Har det med manglende infrastruktur å gjøre, at man får page not found?

**Comment by allinox** [comment]
@rtafj @jonkjetiloye 

I've looked into it, and I think this is a frontend issue.

As far as I can see, the frontend tries to refresh the token every 10 minutes if you're still actively using the page, but if you have left it idle for so long that the 30 min timer has gone out on the token, the refresh call will fail and the frontend tries to send you to https://am.ui.at23.altinn.cloud/ which doesn't actually exist.

This is a bug.

Instead, we should redirect to the login-page and then, after login, to the Profile page so you can move on from there.
Working on a fix like this now 😊
