### ISSUE TITLE
API delegering - resetting of Søk på organisasjonsnummer field

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#385]
Go to API delegering and search for an organization in' Søk på organisasjonsnummer' field
Organization name appears correctly under 'Virksomheter basert på ditt søk:'
Click on Add icon ad organization is now added to 'Virksomheter som skal få rettighet:' list
If you see 'Søk på organisasjonsnummer', this still has old organization number and' Virksomheter basert på ditt søk:' shows nothing.
I was wondering once you add organization, should the 'Søk på organisasjonsnummer' field be reset back to empty such that user can type in a new organization number without going and deleting the old one.

see gif for more info

![Image](https://user-images.githubusercontent.com/117180726/229768401-10959d47-cabb-4773-9df5-127feced2e51.gif)

**Comment by anishastphen** [comment]
@rtafj @jonkjetiloye @Albertlarsen @allinox

**Comment by anishastphen** [comment]
@jonkjetiloye har dere diskutert noe om denne bugen i refinement?

**Comment by jonkjetiloye** [comment]
@anishastphen Jo, vi diskuterte den og er enig i at det er noe vi ønsker å utbedre. Den er ikke strengt nødvendig å fikse før vi går live men kan plukkes av frontend utviklerne når de får tid.
