### ISSUE TITLE
API delegering - dividing line between scopes and beskrivelse

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#387]
Start API delegering
Go to page where you select API for delegation
Expand one API
Inside API, the line between scopes and Beskrivelse is much darker than the line between APIs - it should be the opposite
Or even we can just remove the line between scopes and Beskrivelse?

Applicable for both Delegerbare API and Valgte API list

![Image](https://user-images.githubusercontent.com/117180726/229778354-3169e3d9-3723-4b29-bfa1-35cd42917632.png)

**Comment by anishastphen** [comment]
@rtafj @jonkjetiloye

**Comment by jonkjetiloye** [comment]
Refinement: linjen kan nok fjernes

**Comment by Albertlarsen** [comment]
We've fixed this
