### ISSUE TITLE
API delegering - missing : for Beskrivelse

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#388]
Start API delegering
Go to page where you select API for delegation
Expand one API
Beskrivelse is missing : , it should be same as Scopes

Applicable for both Delegerbare API and Valgte API list

![Image](https://user-images.githubusercontent.com/117180726/229779739-44d9ed32-4889-41e5-9b63-bb4cd9f0473a.png)

**Comment by anishastphen** [comment]
@rtafj @jonkjetiloye

**Comment by jonkjetiloye** [comment]
Refinement: scopes has a colon as it can be a list of items but description is a just a single description. 
conclusion: as designed
