### ISSUE TITLE
API delegering - order for displaying APIs in receipt page

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#390]
I have delegated 3 APIs to 2 organizations 
I am wondering what is the order in which API's and organizations are displayed in receipt page.
Would it be nice if APIs are displayed in alphabetic order and corresponding organizations are displayed OR organizations are displayed in alphabetic order?

![Image](https://user-images.githubusercontent.com/117180726/230019349-6b19059d-b007-450b-bed0-5a93f8477c73.png)

**Comment by anishastphen** [comment]
@rtafj @jonkjetiloye

**Comment by sivaglen** [comment]
Å sortere denne visning på API delegering har liten verdi, men vi bør strukturere kvitteringssiden bedre for kvittering vi lager for delegering av andre tjenestetyper i A3. 
@hannekristin og @Randiabs - følger dere opp dette i design for delegering av lenketjenester?
