### ISSUE TITLE
API delegering - line between organizations in delegations overview page

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#392]
User has delegated APIs to 2 different organizations and is in delegations overview page
The line between organizations looks good when organizations are collapsed.
Now expand the organization

1. Now you see the line dividing organizations looks a little misplaced, it has gone much below the last API of the first org
2. The lines dividing organization is much lighter than the lines dividing APIs within an organization

![Image](https://user-images.githubusercontent.com/117180726/230038634-23c2242e-a381-4586-89a6-1ec2e04fa784.png)

![Image](https://user-images.githubusercontent.com/117180726/230038844-d5d764e1-6a9a-4c1a-a462-c57da8194929.png)

**Comment by anishastphen** [comment]
@rtafj @jonkjetiloye

**Comment by jonkjetiloye** [comment]
Refinement: this view will change once the new actionbar component is done and the views are updated to use this new component, which will add a spacing between each entry
