### ISSUE TITLE
API delegering- delegations overview page when no APIs are delegated

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#393]
Open delegations overview page for an org which has not delegated any API - **Delegerte tilganger til programmerings­grensesnitt - API**
This page should give some message that no APIs are delegated, as user might get confused
The same issue is applicable for **Mottatte tilganger til programmerings­grensesnitt - API** when no delegations are received

![Image](https://user-images.githubusercontent.com/117180726/230040804-f67c5c38-2152-48f2-8203-dc47c62ef049.png)

I see in figma it is specified

![Image](https://user-images.githubusercontent.com/117180726/230040974-fbd21272-15ef-4041-a164-d218bb41d852.png)

**Comment by anishastphen** [comment]
@rtafj @jonkjetiloye

**Comment by jonkjetiloye** [comment]
Refinement: Add text when response is empty

**Comment by Randiabs** [comment]
Ny tekst sjekket i ulike views, ok. Satt til test

**Comment by anishastphen** [comment]
testet OK, lukker issuen
