### ISSUE TITLE
API delegering - delegation of APIs which require higher auth level

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#394]
Login with Altinn pincodes and represent org
Go to API delegation page and delegate an API which requires higher authentication level (3 or 4)
Gets error message that access is not given

It should give error message that to delegate these APIs, user needs to login with higher authentication level

![Image](https://user-images.githubusercontent.com/117180726/230069017-0d1fd7ed-dfef-40c6-96f7-f7411fc9113f.png)

**Comment by anishastphen** [comment]
@rtafj @jonkjetiloye

**Comment by jonkjetiloye** [comment]
Refinement:
@jonkjetiloye will make sure we have issue in BFF backlog to create the CanDelegate function which should be triggered at the moment the service is added to the list of delegations.

**Comment by jonkjetiloye** [comment]
Issue for CanDelegate created in backlog:
https://github.com/Altinn/altinn-access-management-frontend/issues/285
