### ISSUE TITLE
post maskinportenschema with orgno in header returns 403

### ISSUE THREAD

**Issue by ivartryti** [Altinn/altinn-access-management#400]
This fails in PEP/Authorization step of the request when authorization tries to lookup the party based on the organization number header. 

App insights log from reproducing the bug:
https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%2269a84514-efc3-11ed-be15-2de185fcbd57%22,%22timestamp%22:%222023-05-11T06:16:44.4085276Z%22%7D/ComponentId/%7B%22Name%22:%22at22-platform-ai%22,%22ResourceGroup%22:%22altinnplatform-at22-rg%22,%22SubscriptionId%22:%22de41df22-8dd0-435b-98dd-6152cd371e92%22%7D

**Comment by sivaglen** [comment]
Må fixes før vi kan åpne API for delegering av eksterne.

**Comment by rtafj** [comment]
@sivaglen @jonkjetiloye  må denne fikses før vi slipper SKE til på API?

**Comment by jonkjetiloye** [comment]
Nei, dette gjelder bare håndtering av valgt avgiver i sluttbruker/system API for å hente og utføre API-delegeringer.
Så påvirker ikke tjenesteiers API for opprettelse av ressurser eller uthenting av maskinporten/delegations basert på scope.
