### ISSUE TITLE
API delegering - 'Virksomheter det tidligere er delegert til:' when there are no organizations

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#409]
Start API delegering
User should not have delegated API to any org
Go to page where you add organization
There you can see - **Virksomheter det tidligere er delegert til:** even if you haven't delegated API to any org
Wondering if we need this when there are no existing delegations

![Image](https://user-images.githubusercontent.com/117180726/233056588-8593ff02-d4ed-435c-92b3-e6c26b880512.png)

**Comment by anishastphen** [comment]
@rtafj @jonkjetiloye

**Comment by jonkjetiloye** [comment]
@anishastphen personally I would think this was 'as designed', but from the figma design I see the header isn't even there to tell the user the list contains organizations which has already received delegations.

@hannekristin I guess this is more of a design review issue?

**Comment by sivaglen** [comment]
@hannekristin - jeg lukker denne. Protester hvis du er uenig :)
