### ISSUE TITLE
API delegering - org no not crossed out when deleting

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#412]
Go to delegations overview page where org has delegated APIs
Click on Rediger tilgang ang click on Slett corresponding to org
The whole content is crossed  out, except the org no
Wondering if org no should also be the same?

![Image](https://user-images.githubusercontent.com/117180726/233354225-32ee7214-1731-4fe4-82f9-8cfe623c564c.png)

**Comment by anishastphen** [comment]
@rtafj @jonkjetiloye @Albertlarsen @allinox

**Comment by Albertlarsen** [comment]
I'll fix this in #230

**Comment by sivaglen** [comment]
[#230](https://github.com/Altinn/altinn-access-management-frontend/issues/230) er lukket så vi lukker denne også.

**Comment by sivaglen** [comment]
@anishastphen tester du denne ved anlegning?

**Comment by anishastphen** [comment]
testet ok
