### ISSUE TITLE
API delegering - org no in English

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#413]
Small thing - I believe Org.nr. should be shown as Org.no. in English

![Image](https://user-images.githubusercontent.com/117180726/233609017-b29002e3-b26a-40b9-a37d-6c0f6ad15733.png)

**Comment by anishastphen** [comment]
@rtafj @jonkjetiloye @Albertlarsen

**Comment by sivaglen** [comment]
@hannekristin, @Randiabs - i teorien skal dere kunne endre denne teksten i tekstressursfilene. Kan dere bruke denne issuen (med hjelp av @Albertlarsen eller @allinox ) til å finne ut hvordan det gjøres.

**Comment by rtafj** [comment]
@hannekristin @Randiabs - kan dere oppdatere tekstressursfilene med riktig engelsk?

**Comment by hannekristin** [comment]
Rettet
