### ISSUE TITLE
API delegring - API in capital letters

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#415]
Will be good if we have API in below screenshot in capital letters

![Image](https://user-images.githubusercontent.com/117180726/233618136-c6dad85e-1962-41ba-b526-49c442b8f0d6.png)

**Comment by anishastphen** [comment]
@rtafj @jonkjetiloye @Albertlarsen

**Comment by Albertlarsen** [comment]
Fixed now
