### ISSUE TITLE
API delegering - possibe to delegate API using Altinn2 REST endpoints

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#416]
Feature toggle MaskinportenDelegationsDisableAltinnII and MaskinportenDelegationsInAltinnPlatform is enabled
Using Altinn2 REST endpoint, delegate an API to an org

Endpoint - https://at23.altinn.cloud/api/910459597/authorization/delegations
{
    "Type": "Email",
    "Email": "anisha.ann.stephen@accenture.com",
    "OrganizationNumber": "910474901",
    "Name": "LIMINGEN OG HOL I TJELDSUND REGNSKAP",
    "_embedded" : {
        "Rights" : [{
            "ServiceCode": "AppId:413",
            "ServiceEditionCode": "1",
            "Action": "Read"
        }]
    }
}

**I get response, 201 created which is not correct, as this should not be possible now**

Receiver also gets email
Hi,
LIMINGEN OG HOL I TJELDSUND have received the following rights in Altinn on behalf of HJELLESTAD OG VEIDNESKLUBBEN:
- 1Automation Regression_

When I go to Profile for 910459597 and check 'Andre med rettigheter', I see LIMINGEN OG HOL I TJELDSUND in the list.
If I open it, I don't see any delegations

![Image](https://user-images.githubusercontent.com/117180726/233993350-3b8b64e4-f198-4577-be32-a5fc36064bbc.png)

![Image](https://user-images.githubusercontent.com/117180726/233993477-229aca9a-878f-46d9-9bfd-44536540ec1b.png)

**Comment by anishastphen** [comment]
@jonkjetiloye @rtafj @lovoll

**Comment by Albertlarsen** [comment]
Dette er fikset
