### ISSUE TITLE
API delegering - delegering feiler noen ganger uten spesielle grunn

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#424]
Jeg har sett at API delegeringer feiler uten noe spesielle grunn
Men etter noe forsøk, funker det
Det ser ut som litt ustabil noen ganger, men kan ikke reproduseres siden det funker etter noe forsøk
Har oppølevd etter jeg trekker roller for en bruker og prøver å delegere API igjen

Snakket litt med Jon Kjetil og han synes det kan være noe forskjeller i caching mellom BFF og backend accessmanagement (evt mellom forskjellige pods/servere på backend)

**Comment by anishastphen** [comment]
@jonkjetiloye @rtafj  @lovoll

**Comment by jonkjetiloye** [comment]
@anishastphen @TheTechArch 
Dette lukter av in-memory caching pr. pod/server problematikk for min del. 

Ved endring i en brukers roller tar det inntil 5 minutter før evt. eksisterende caching er utløpt på alle pods både i authorization (PDP) og accessmanagement (delegering).

I den perioden kan det dersom det eksisterer cachede uttrekk av en brukers roller (fra før man fikk eller mistet en ny rolle) på en eller flere pods, kan man oppleve løsningen som ustabil og at man blir autorisert OK for ett steg men bli avslått i neste steg.

**Comment by jonkjetiloye** [comment]
Vi har oppdaget og utbedret en mangel i løsningen knytt til bruken av XSRF tokens som har skapt ustabilitet knytt til skalering av access management ui frontend applikasjonen. Dette skapte feil både når applikasjonen skalerte helt ned til 0 og så starter en ny instans/replica eller når den skalerte opp til flere instanser slik at behandling av requests fra GUI tl BFF-laget ikke lenger er 1-1.

Dette er nå utbedret i AT22 som nå også er konfigurert for skalering 2-10 replicas slik at det alltid skal være minimum 2 kjørende instanser av applikasjonen.

@sivaglen @rtafj 
Dette må vi også få med i endelige løsningen før vi kan gå i prod, og inkluderer enda en komponent (storage account) som må inkluderes i infrastruktur oppsettet pr. miljø.

@anishastphen 
Får du testet litt på nytt i AT22 for å se om problemene du også har opplevd nå er løst?

Utviklerne har testet noe selv etter deployen til AT22 i går og ser i hvertfall ut som hovedproblemet vi har opplevd ved delegering eller trekking av mange delegeringer samtidig er løst.

**Comment by anishastphen** [comment]
testet og ser bra ut
