### ISSUE TITLE
API delgering - org name not shown correctly

### ISSUE THREAD

**Issue by anishastphen** [Altinn/altinn-access-management#445]
In API delegation page, search for org 810438312
Org name is HORDVIK OG HUSTAD 
When I search for it, it is shown as below in the screenshot

![Image](https://github.com/Altinn/altinn-access-management/assets/117180726/3641bbbf-6886-46cc-a7a0-61fabd358b75)

Name is shown incorrect in all API delegering pages

But in delegations overview page, it is shown correct

![Image](https://github.com/Altinn/altinn-access-management/assets/117180726/271fa3bc-b27c-47ab-b02d-2b6d2a778cc6)

**Comment by jonkjetiloye** [comment]
@anishastphen @rtafj This seems to be an issue with this specific organization:
`OrgNumber_AK	EditedName	UnitName
810438312	HêãO.RDVIK OG HUSTAD	HORDVIK OG HUSTAD`

Although edited name shouldn't really be used anyway.. so it depends where the selection of name happens.

The BFF lookup returns the entire Party object so either I guess it's the frontend react component either needs to be updated to select the other name in the model, or this is a bug to Altinn.Platform.Register to not use the edited name of organizations when mapping the Altinn 2 Party to it's Altinn 3 equivalent model.

**Comment by jonkjetiloye** [comment]
seems like the mapping error is done in the Altinn 2 SBL Bridge API,
where EntityMapper.GetPartyBEName uses party.Organization.EditedName

**Comment by anishastphen** [comment]
so to whom should this be assigned?
do you think it should be resolved soon? Dont think there should be a difference in EditedName and UnitName for orgs in prod

**Comment by jonkjetiloye** [comment]
@annerisbakk @SandGrainOne 
This is an issue with the "register/api/v1/parties/lookup" API whose lookup in the SBL bridge use a mapping of the party.Organization.EditedName. Since a change can effect others using the register API I feel it's a change perhaps the platform team should own.

**Comment by anishastphen** [comment]
assigning to Anne so that she can do the required

**Comment by SandGrainOne** [comment]
Is this at least partiall a duplicate of https://github.com/Altinn/altinn-register/issues/79?

**Comment by rtafj** [comment]
@SandGrainOne  They are at least related, and should be fixed together. 
EditedName should not be used anywhere in code, and SBLBridge needs to use UnitName instead.

**Comment by Albertlarsen** [comment]
Will be fixed by team core in this task https://github.com/Altinn/altinn-register/issues/79
