### ISSUE TITLE
Populate CompanyRequestsAccordionContent with data

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-access-management#46]
Populate the lists in CompanyRequestsAccordionContent using the new backend api calls. The Api call takes userId as input so this task #45  needs to be done first

- [x] New easy-to-read file and folder structure for api calls
- [x] New easy-to-read file and folder types used in api calls
- [x] Added new fields to DelegationRequest
- [x] Mapping functionality to list all requests

**Comment by sivaglen** [comment]
@Albertlarsen er denne klar til testing? Eller er det en annen grunn til at det ligger i icebox?

**Comment by Albertlarsen** [comment]
@sivaglen Svaret er nok nei for vi fikk aldri deployet CompanyRequestsAccordionContent fordi vi begynte å jobbe med ny react-app og api-delegering før vi kom så langt at vi fikk sluppet dette i et miljø det går an å teste i.

**Comment by Albertlarsen** [comment]
@sivaglen flyttet den fra ice box til closed.
