### ISSUE TITLE
Beskriv hva ulike verdier av RightSourceType betyr i forbindelse med RIGHTS LOOKUP

### ISSUE THREAD

**Issue by sivaglen** [Altinn/altinn-access-management#468]
I forbindelse med tjenesten   /{party}/rights/lookup/ i A3 API (for sluttbrukersystem) så skal man oppgi informajson om SourceType som vil si hvorfor en bruker har en rettighet på vegne av party (avgiver). 

Vi trenger en beskrivelse av hva de ulike verdiene som skal retureneres betyr i kontekst av organisasjon og person. 

OrganisationRightsLookUp: 
- Right
- RightToKeyRoleUnit
- RightFromMainUnit
- RightFromMainUnitToKeyRoleUnit
- Role
- RoleToKeyRoleUnit
- RoleFromMainUnit
- RoleToFromMainUnitKeyRoleUnit

PersonRightsLookUp: 
- Right
- RightToKeyRoleUnit
- RightFromMainUnit
- RightFromMainUnitToKeyRoleUnit
- Role
- RoleToKeyRoleUnit
- RoleFromMainUnit
- RoleToFromMainUnitKeyRoleUnit

**Comment by jonkjetiloye** [comment]
**RightSourceType:**
- 'Right'
- 'RightToKeyRoleUnit'
- 'RightFromMainUnit'
- 'RightFromMainUnitToKeyRoleUnit'
- 'Role'
- 'RoleToKeyRoleUnit'
- 'RoleFromMainUnit'
- 'RoleFromMainUnitToKeyRoleUnit'


**Person A**: Privatperson
**Person B**: DAGL for Virksomhet E
**Person C**: DAGL for Virksomhet F
**Person D**: DAGL for Hovedenhet H (og Underenhet U)


**Virksomhet E**
**Virksomhet F**
**Hovedenhet H**
- **Underenhet U**

**Hovedenhet H2**
- **Underenhet U2**


## Avgiver: Person A Privatperson

### Mottatte rettigheter til Person A (/person/rights/lookup/received):

**Right:** Rettighet gitt direkte til Person A
**RightToKeyRoleUnit:** Vil ikke forekomme gitt at Person A ikke har nøkkelrolle
**RightFromMainUnit:** Rettighet gitt direkte til Person A fra 	Hovedenhet H. Vil bare kunne forekomme dersom "from" i oppslaget er Underenhet U.
**RightFromMainUnitToKeyRoleUnit:** Vil ikke forekomme gitt at Person A ikke har nøkkelrolle
**Role:** Rettighet gjennom rolle gitt direkte til Person A
**RoleToKeyRoleUnit:** Vil ikke forekomme gitt at Person A ikke har nøkkelrolle
**RoleFromMainUnit:** Rettighet gjennom rolle gitt direkte til Person A fra Hovedenhet H. Vil bare kunne forekomme dersom "from" i oppslaget er Underenhet U.
**RoleFromMainUnitToKeyRoleUnit:** Vil ikke forekomme gitt at Person A ikke har nøkkelrolle

### Gitte rettigheter fra Person A (/person/rights/lookup/offered):

**Right:** Rettighet gitt direkte fra Person A
**RightToKeyRoleUnit:** Rettighet gitt fra Person A til Virksomhet E. Vil bare forekomme dersom "to" i oppslaget er Person B.
**RightFromMainUnit:** Vil ikke forekomme siden Person A ikke er en underenhet.
**RightFromMainUnitToKeyRoleUnit:** Vil ikke forekomme siden Person A ikke er en underenhet.
**Role:** Rettighet gjennom rolle gitt direkte fra Person A
**RoleToKeyRoleUnit:** Rettighet gjennom rolle gitt fra Person A til Virksomhet E. Vil bare forekomme dersom "to" i oppslaget er Person B.
**RoleFromMainUnit:** Vil ikke forekomme siden Person A ikke er en underenhet.
**RoleFromMainUnitToKeyRoleUnit:** Vil ikke forekomme siden Person A ikke er en underenhet.


## Avgiver: Person B DAGL i virksomhet

### Mottatte rettigheter for Person B (/person/rights/lookup/received):

**Right:** Rettighet gitt direkte til Person B
**RightToKeyRoleUnit:** Rettighet gitt til Virksomhet E
**RightFromMainUnit:** Rettighet gitt direkte til Person B fra Hovedenhet H. Vil bare kunne forekomme dersom "from" i oppslaget er Underenhet U.
**RightFromMainUnitToKeyRoleUnit:** Rettighet gitt til Virksomhet E fra Hovedenhet H. Vil bare kunne forekomme dersom "from" i oppslaget er Underenhet U.
**Role:** Rettighet gjennom rolle gitt direkte til Person B
**RoleToKeyRoleUnit:** Rettighet gjennom rolle gitt til Virksomhet E
**RoleFromMainUnit:** Rettighet gjennom rolle gitt direkte til Person B fra Hovedenhet H. Vil bare kunne forekomme dersom "from" i oppslaget er Underenhet U.
**RoleFromMainUnitToKeyRoleUnit:** Rettighet gjennom rolle gitt til Virksomhet E fra Hovedenhet H. Vil bare kunne forekomme dersom "from" i oppslaget er Underenhet U.

### Gitte rettigheter fra Person B (/person/rights/lookup/offered):

Identisk scenario som Gitte rettigheter fra Person A


## Avgiver: Virksomhet E

### Mottatte rettigheter til Virksomhet E (/organization/rights/lookup/received):

**Right:** Rettighet gitt direkte til Virksomhet E
**RightToKeyRoleUnit:** Vil ikke forekomme gitt at Virksomhet E ikke kan ha nøkkelrolle ???
**RightFromMainUnit:** Rettighet gitt direkte til Virksomhet E fra Hovedenhet H. Vil bare kunne forekomme dersom "from" i oppslaget er Underenhet U.
**RightFromMainUnitToKeyRoleUnit:** Vil ikke forekomme gitt at Virksomhet E ikke kan ha nøkkelrolle ???
**Role:** Rettighet gjennom rolle gitt direkte til Virksomhet E
**RoleToKeyRoleUnit:** Vil ikke forekomme gitt at Virksomhet E ikke kan ha nøkkelrolle ???
**RoleFromMainUnit:** Rettighet gjennom rolle gitt direkte til Virksomhet E fra Hovedenhet H. Vil bare kunne forekomme dersom "from" i oppslaget er Underenhet U.
**RoleFromMainUnitToKeyRoleUnit:** Vil ikke forekomme gitt at Virksomhet E ikke kan ha nøkkelrolle ???

### Gitte rettigheter fra Virksomhet E (/organization/rights/lookup/offered):

**Right:** Rettighet gitt direkte fra Virksomhet E
**RightToKeyRoleUnit:** Rettighet gitt fra Virksomhet E til Virksomhet F. Vil bare forekomme dersom "to" i oppslaget er Person C.
**RightFromMainUnit:** Vil ikke forekomme siden Virksomhet E ikke er en underenhet.
**RightFromMainUnitToKeyRoleUnit:** Vil ikke forekomme siden Virksomhet E ikke er en underenhet.
**Role:** Rettighet gjennom rolle gitt direkte fra Virksomhet E
**RoleToKeyRoleUnit:** Rettighet gjennom rolle gitt fra Virksomhet E til Virksomhet F. Vil bare forekomme dersom "to" i oppslaget er Person C.
**RoleFromMainUnit:** Vil ikke forekomme siden Virksomhet E ikke er en underenhet.
**RoleFromMainUnitToKeyRoleUnit:** Vil ikke forekomme siden Virksomhet E ikke er en underenhet.


## Avgiver: Underenhet U

### Mottatte rettigheter til Underenhet U (/organization/rights/lookup/received):

**Right:** Rettighet gitt direkte til Underenhet U
**RightToKeyRoleUnit:** Vil ikke forekomme gitt at Underenhet U ikke kan ha nøkkelrolle ???
**RightFromMainUnit:** Rettighet gitt direkte til Underenhet U fra Hovedenhet H2. Vil bare kunne forekomme dersom "from" i oppslaget er Underenhet U2.
**RightFromMainUnitToKeyRoleUnit:** Vil ikke forekomme gitt at Underenhet U ikke kan ha nøkkelrolle ???
**Role:** Rettighet gjennom rolle gitt direkte til Underenhet U
**RoleToKeyRoleUnit:** Vil ikke forekomme gitt at Underenhet U ikke kan ha nøkkelrolle ???
**RoleFromMainUnit:** Rettighet gjennom rolle gitt direkte til Underenhet U fra Hovedenhet H2. Vil bare kunne forekomme dersom "from" i oppslaget er Underenhet U2.
**RoleFromMainUnitToKeyRoleUnit:** Vil ikke forekomme gitt at Underenhet U ikke kan ha nøkkelrolle ???

### Gitte rettigheter fra Underenhet U (/organization/rights/lookup/offered):

**Right:** Rettighet gitt direkte fra Underenhet U
**RightToKeyRoleUnit:** Rettighet gitt fra Underenhet U til Virksomhet F. Vil bare forekomme dersom "to" i oppslaget er Person C.
**RightFromMainUnit:** Rettighet gitt fra Hovedenhet H
**RightFromMainUnitToKeyRoleUnit:** Rettighet gitt fra Hovedenhet H til Virksomhet F. Vil bare forekomme dersom "to" i oppslaget er Person C.
**Role:** Rettighet gjennom rolle gitt direkte fra Underenhet U
**RoleToKeyRoleUnit:** Rettighet gjennom rolle gitt fra Underenhet U til Virksomhet F. Vil bare forekomme dersom "to" i oppslaget er Person C.
**RoleFromMainUnit:** Rettighet gjennom rolle gitt fra Hovedenhet H
**RoleFromMainUnitToKeyRoleUnit:** Rettighet gjennom rolle gitt fra Hovedenhet H til Virksomhet F. Vil bare forekomme dersom "to" i oppslaget er Person C.
