### ISSUE TITLE
Analysis serviceowner API; use of ssn in query

### ISSUE THREAD

**Issue by rtafj** [Altinn/altinn-access-management#469]
### Description
*Vi må avklare om vi kan bruke ssn som spørringsparameter i nye A3 API-er for tjenesteeier.*

*I gjeldende A2 serviceowner-API getRights/getReportees/getRoles brukes ssn som spørringsparameter i dag, og gjør at disse APIene kan implementeres som en HTTP GET-operasjon, som følger "normale" REST-prinsipper. 
Imidlertid er spørringsparametere vanligvis inkludert i serverlogger (IIS etc) for både utgående logger for tjenesteeieren og Altinns inngående logger. De beste alternativene for å unngå dette er enten:*

*- GET-forespørsel, men oppgi ssn som headerverdier*
*- POST-forespørsel gir innspillet i request body*
*- Det antas derfor at dette ikke er en praksis vi bør fortsette med når vi designer nye tjenesteeier-APIer i A3.*

*Noe av grunnen til denne avklaringen er at det allerede er kjent at enkelte tjenesteeiere kanskje ikke er enige i denne avgjørelsen, og teamet ønsker derfor å få en vurdering av problemet fra et personvernstandpunkt fra Team Juridisk.
(Se eksempler under)*

We need to clarify if we can use ssn as query-parameter in new A3 API's for serviceowner.

In the current A2 serviceowner-API getRights/getReportees/getRoles , ssn is used as query parameter today, and allows for these APIs to be implemented as an HTTP GET operation, which is following "normal" REST principles.

However query parameters are usually included in server logs (IIS etc) for both outbound logs for the service owner and Altinns inbound logs. The best alternatives to avoid this is either:
- GET request but provide the ssn as header values
- POST request providing the input as a request body

It's therefore assumed that this is not a practice we should continue for when designing new service owner APIs in A3. 

Part of the reason for this clearification is that it is already known that some service owners might not agree with this decision, and the team would therefore like to get an evaluation of the issue from a privacy stand point from Team Juridisk.

#### GET following REST principles
```
curl -X 'GET' \
  'https://platform.at22.altinn.cloud/accessmanagement/serviceowner/api/v1/rights?from=15923648388&to=22828473666&resource=urn%3Aaltinn%3Aresource%3Attd-someresourceid' \
  -H 'accept: application/json'
```

#### GET using header values
```
curl -X 'GET' \
  'https://platform.at22.altinn.cloud/accessmanagement/serviceowner/api/v1/rights?resource=urn%3Aaltinn%3Aresource%3Attd-someresourceid' \
  -H 'accept: application/json' \
  -H 'from: 15923648388' \
  -H 'to: 22828473666'
```

#### POST using request body
```
curl -X 'POST' \
  'https://platform.at22.altinn.cloud/accessmanagement/serviceowner/api/v1/rights' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "from": [
    {
      "id": "urn:altinn:ssn",
      "value": "15923648388"
    }
  ],
  "to": [
    {
      "id": "urn:altinn:ssn",
      "value": "22828473666"
    }
  ],
  "resource": [
    {
      "id": "urn:altinn:resource",
      "value": "ttd-someresourceid"
    }
  ]
}'
```

### Additional Information / Ekstra informasjon
*- I en rask diskusjon med sikkerhetsansvarlig, var han enig i vår antagelse om at vi ikke skulle fortsette praksisen med å få ssn-inndata som spørringsparametere i GET-forespørsler*
*- Arkitektene i både Tilgangsstyring og i TIlgangsinfo heller mot å benytte POST-kall.*

- In a quick discussion the security lead, he agreed to our assumption that we should not continue the practice of getting ssn input as query params in GET requests
- Both authorization team architects tend to lean towards the POST request approach

### Conclusion

Logging av identifikasjonsnummer er en behandling av personopplysninger. 

Etter personopplysningsloven § 12 kan fødselsnummer og andre entydige identifikasjonsmidler bare behandles når det er saklig behov for sikker identifisering og metoden er nødvendig for å oppnå slik identifisering. I tråd med personvernprinsippene skal man sørge for innebygd personvern og personvern som standardinnstilling, jf. personvernforordningen artikkel 25. Kun personopplysninger som er nødvendige for behandlingen skal behandles. I henhold til prinsippet om dataminimering skal man begrense innsamling og viderebehandling av personopplysninger til kun det som er nødvendig. 

I dette tilfellet kan vi ikke se at det foreligger noe saklig behov eller formål i henhold til personopplysningsloven som gjør at vi kan legge til rette for logging av identifikasjonsnummer i utgående logger for tjenesteeier og inngående logger for Altinn, i og med at ønsket formål kan oppnås på annen måte. Herunder slik dere har beskrevet dette med POST-kall og GET-forespørsel med ssn som headerverdi. En av disse fremgangsmåtene skal benyttes.

### Dokumentasjon

- Juridisk vurdering[ ligger her](https://digdir.sharepoint.com/:w:/r/sites/TeamJuridiskDGT/Delte%20dokumenter/Produktteam/Team%20Tilgangsstyring%20og%20kontroll/%23469%20Analysis%20serviceowner%20API%20-%20use%20of%20ssn%20in%20query.docx?d=w716cdefece914d289c1cab245167d62b&csf=1&web=1&e=qzonk3)

**Comment by rtafj** [comment]
@jonkjetiloye  Kan du legge til info om de ulike alternativene?

**Comment by jonkjetiloye** [comment]
@rtafj @benedicteos har oppdatert med litt mer beskrivelse og eksempler på løsningsalternativene

**Comment by rtafj** [comment]
@benedicteos @Oddhild  - har lagt inn norsk tekst i kursiv

**Comment by benedicteos** [comment]
@rtafj , @jonkjetiloye 

Her er vår juridiske vurdering: 

Logging av identifikasjonsnummer er en behandling av personopplysninger. 

Etter personopplysningsloven § 12 kan fødselsnummer og andre entydige identifikasjonsmidler bare behandles når det er saklig behov for sikker identifisering og metoden er nødvendig for å oppnå slik identifisering. I tråd med personvernprinsippene skal man sørge for innebygd personvern og personvern som standardinnstilling, jf. personvernforordningen artikkel 25. Kun personopplysninger som er nødvendige for behandlingen skal behandles. I henhold til prinsippet om dataminimering skal man begrense innsamling og viderebehandling av personopplysninger til kun det som er nødvendig. 

I dette tilfellet kan vi ikke se at det foreligger noe saklig behov eller formål i henhold til personopplysningsloven som gjør at vi kan legge til rette for logging av identifikasjonsnummer i utgående logger for tjenesteeier og inngående logger for Altinn, i og med at ønsket formål kan oppnås på annen måte. Herunder slik dere har beskrevet dette med POST-kall og GET-forespørsel med ssn som headerverdi. En av disse fremgangsmåtene skal benyttes.

**Comment by jonkjetiloye** [comment]
lukker saken da den er ferdig avklart med jus
