### ISSUE TITLE
design av GUI for aktivitetslogg i A3

### ISSUE THREAD

**Issue by rtafj** [Altinn/altinn-access-management#489]
Oppgave for å lage fane komponent https://github.com/Altinn/altinn-access-management/issues/516

**Comment by Randiabs** [comment]
Foreløpig skisser:



![Image](https://github.com/Altinn/altinn-access-management/assets/94835837/d6ddf3c6-fe4c-426f-899b-29a9494ab505)





![Image](https://github.com/Altinn/altinn-access-management/assets/94835837/7f768b14-f962-450f-9880-953907561cd3)

**Comment by Randiabs** [comment]
Opprettet eget issue #516 , lukker denne.
