### ISSUE TITLE
MaskinportenSchema K6 tests broken because of model change for Action

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#520]
### Description of the bug

Ref. Testrun: https://dev.azure.com/brreg/altinn-studio/_build/results?buildId=836793&view=ms.vss-test-web.build-test-results-tab
9 tests are failing MaskinportenSchema delegation currently because of change made to the RightsBasic model where Action is no longer an AttributeMatch model but just a single string value. 

### Steps To Reproduce

1. Run existing MaskinportenSchema K6 tests

**Comment by Albertlarsen** [comment]
Wait with this until Ivar's guide on K6 tests is finished

**Comment by ivartryti** [comment]
Fikset i https://github.com/Altinn/altinn-access-management/pull/580
