### ISSUE TITLE
sblbridge/.../userdelegationcheck respons mangler attributematch for "action"

### ISSUE THREAD

**Issue by ivartryti** [Altinn/altinn-access-management#521]
Denne spørringen returnerer en liste med RightDelegationStatus, men "action" og "status" er ikke attributematch
https://at22.altinn.cloud/sblbridge/authorization/api/rights/delegation/userdelegationcheck?userId=20004896&partyId=50067258&serviceCode=2802&serviceEditionCode=2203

**Comment by jonkjetiloye** [comment]
@ivartryti denne er vel løst og kan lukkes?

**Comment by ivartryti** [comment]
Yep, lukker denne!
