### ISSUE TITLE
Placeholder for A2-oppgave: Ressurser i ressursregisteret må vises i listen over tjenester som en rolle gir tilgang til

### ISSUE THREAD

**Issue by rtafj** [Altinn/altinn-access-management#607]
https://dev.azure.com/digdir/Altinn/_workitems/edit/63803

**Comment by acn-Sneha** [comment]
@rtafj @Siri-Anna @nairaz @jonkjetiloye - Vi har ikke automatisert testing for den da lager jeg nye task for å dekke e2e test for den og lukker denne tasken
