### ISSUE TITLE
Tilgangsstyring på ressurser som har regler i RRR

### ISSUE THREAD

**Issue by rtafj** [Altinn/altinn-access-management#621]
### Description

Tilgangsstyring må utvides til å sjekke om det finnes regler i RRR på ressursen. Dersom valgt avgiver ikke er knyttet til en RRR-regel for ressursn, skal det ikke være mulig å deleger ressursen på vegne av denne avgiveren.

PDP håndteres av Tilgangsinfo.

**Comment by annerisbakk** [comment]
Lukkes. Erstattes av #699
