### ISSUE TITLE
Åpne opp for å kunne registrere enkeltdelegering på en ressurs

### ISSUE THREAD

**Issue by Sondre-B** [Altinn/altinn-access-management#63]
### Description

Utvide Delegation APIet med mulighet for delegering av enkeltdelegering på en ressurs fra resource registry.

Lenke til Epic:
https://github.com/Altinn/altinn-authorization/issues/62

### Additional Information

Det er behov for et endepunkt på DelegationsControlleren for å kunne registrere en delegering av rettigheter for en ressurs.

### Acceptance Criterias

Mulig å registrere ressursdelegering via endepunkt på /authorization/api/v1/Delegations/AddResourceDelegation.

**Comment by jonkjetiloye** [comment]
internal implementation only used and tested by implementation of #173
