### ISSUE TITLE
Mer strukturert logging

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#640]
### Description

Ref. demo av Aleksander forrige fredag, ønsker vi å begynne å skrive om måten vi logger på.

### Tasks

- [ ]

**Comment by acn-Sneha** [comment]
@jonkjetiloye @Thuen @andreasisnes Lukker tasken og ref for andre task som er knyttet med den : 
https://github.com/Altinn/altinn-access-management/issues/643
