### ISSUE TITLE
Review av Bruno test-dekning for API delegering

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#641]
### Description

Gå gjennom API delegering K6 testene og det som er migrert til Bruno for å vurdere testdekning på MaskinportenSchema

```[tasklist]
#### MaskinportenSchema
- [ ] GetMaskinportenDelegations (Issues 175, 299, 326, 377)
- [ ] DelegationCheck (Issues 277)
- [x] Delegate (Issues 173, 277)
- [ ] GetOffered (Issues 79, 277)
- [ ] RevokeOffered (Issues 179, 277)
- [ ] GetReceived (Issues 122, 277)
- [ ] RevokeReceived (Issues 179, 277)
```

### Tasks

Review existing test coverage of automated tests in Bruno

### Acceptance Criterias

Create issues for test design and implementation for those API without coverage

**Comment by ivartryti** [comment]
Lagde en issue på å lage Bruno-tester for økt testdekning:
#824

**Comment by ivartryti** [comment]
Lagde issue for bruno-tester for DelegationCheck (Issues 277)
#828

**Comment by jonkjetiloye** [comment]
Bruker ikke mer tid på gamle bruno test dekning på "gamle" API nå. Nye tester skal leveres sammen med nytt Enduser API
