### ISSUE TITLE
Sub-unit missing from reportee response

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management#689]
### Description of the bug

When reporting for a sub-unit, the call to fetch the reportee (if they exist in the users reportee list) fails.

The sub-unit is visible when in A2, but in A3, it is not.
This doesn't really affect the functionality of the delegation process (the user can still delegate as normal), but it might confuse the user, or make it more difficult to know who they are delegating on behalf of.

A2:
![image](https://github.com/Altinn/altinn-access-management/assets/22012997/46514845-1a9e-43d9-a7b4-fe2d0218a74e)

A3:
![image](https://github.com/Altinn/altinn-access-management/assets/22012997/926155d7-3f72-4346-8f8e-461f3c159ec1)

### Steps To Reproduce

1. Log in as as someone with access to a sub-unit
2. Go to 'Andre med rettigheter..' and choose someone to delegate to
3. Observe that the user is reporting for the subunit (top right corner)
4. Click the button to navigate to the delegation process (in A3)
5. Observe that the subunit is no longer visible in the top corner (and the call to fetch it failed)

**Comment by jonkjetiloye** [comment]
Tested OK in AT22 after bugfix deploy 👍 

![Image](https://github.com/Altinn/altinn-access-management/assets/40996230/5c8fbffc-37c2-4b40-bd2e-f006278ae475)
