### ISSUE TITLE
Tilgangspakker-L1 | Virksomheter skal kunne delegere tilgangspakker

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management#731]
## Beskrivelse
Virksomheter skal kunne delegere tilgangspakker til brukere og andre virksomheter.

## Definisjoner
`Systembruker` - "bruker" opprettet for en gitt avgiver (eller "eier" av systembruker) og er entiteten som skal motta delegering av tilganger.

## Hva skal leveres
Vi må ha et API for å kunne utføre delegering av pakker. Det skal kunne delegeres én og én av gangen.
Dette må kunne utvides til delegering til grupper senere.

### Hvem skal kunne delegeres til?
Det er kun virksomheter som skal kunne delegerer pakker i denne omgang
Personer o.l. kan delegere på vegne av virksomheter, men ikke for seg selv eller andre personer.

| fra \ til                           | Person | Virksomhet | Virksomhetsbruker (skal fases ut) | Systembruker | Selvidentifisert |
|-------------------------------|------------|----------------|---------------------------|--------------------|-------------------- |
| **Virksomhet**             |  ✅         | ✅             |  🚫                         |  ✅                 | 🚫                    |

(Note: Delegering på vegne av personer og selvidentifiserte brukere skal komme senere)

## Akseptansekriterier

- Kun Hovedadministrator og Tilgangstyrer skal kunne delegere tilgangspakker
  - Dvs. De som har tilgang til systemresursen altinn_access_management (i Resursregisteret)
- Det skal kun være mulig for tilgangstyrer å delegere pakker bruker selv har tilgang til (hovedadmin kan delegere alt)
- Det skal bare kunne delegeres tilgangspakker som er markert i modellen at den kan delegeres
 - Dvs. Det finnes visse pakker som ikke kan delegeres
- Tilgangspakker for klientdelegering skal ikke være mulig å delegere gjennom dette APIet
- Om man prøver å delegere en pakke til noen som ikke kan motta den skal operasjonen sperres
- Kun tilgangspakker med type Virksomhet skal kunne delegeres i denne omgang

# Involverte Fagområder

```[tasklist]
### Backend
- [ ] Tilgangspakker-L1 | Oppslag av alle tilgangspakker bruker kan delegere på vegne av avgiver
```

```[tasklist]
### Test
- [ ] Tilgangspakker-L1 | Bruno tester for delegering av tilgangspakker
```

```[tasklist]
### Dokumentasjon
```

**Comment by rtafj** [comment]
Tas videre i https://github.com/Altinn/altinn-authorization-tmp/issues/43
