### ISSUE TITLE
Tilgangspakker-L1 | Man skal kunne se hvilke delegeringer av tilgangspakker man har mottatt

### ISSUE THREAD

**Issue by allinox** [Altinn/altinn-access-management#733]
## Beskrivelse
Det skal være mulig for brukere og virksomheter å se hvilke tilgangspakker som de har mottatt og hvilke virksomheter det er på vegne av.

### Hva skal leveres
Det skal leveres backend støtte med Endepunkt for å kunne hente ut hvilke delegeringer som er mottatt for en gitt aktør og hvem delegeringen er gitt på vegne av.
Det skal ikke leveres GUI for dette per nå. (?????)

## Definisjoner
`Aktør` - med aktør menes en som utfører en handling. Dette kan være en person, en virksomhet, en systembruker, eller en selvidentifisert bruker. 
`Undervirksomhet` - Et datterselskap av en virksomhet. F.eks. en bydel i Oslo kommune. Disse arver visse rettigheter fra hovedorvanisasjonen.

## Avklaringer:
- Hvem skal ha lov til å se hva?
- Skal det leveres GUI her?
- Skal man se hvem som utførte delegeringen? Nei - det skal stå i aktivitetslogg

## Akseptansekriterier
- Det skal returneres en liste over hvilke tilgangspakker som er mottatt og hvilken virksomhet de er lenket til
  - Støtte for tilgangspakker for privatpersoner kommer senere
- Arvede tilgangspakker skal også komme i denne listen
  - Dvs. Pakker arvet fra parent virksomheter til undervirsksomheter eller gjennom ER roller

```[tasklist]
### Backend
- [ ] Add a draft title or issue reference here
```

```[tasklist]
### Test
- [ ] Skal bruno tester her??
```

```[tasklist]
### Dokumentasjon
- [ ] Add a draft title or issue reference here
```

**Comment by rtafj** [comment]
Tas videre i https://github.com/Altinn/altinn-authorization-tmp/issues/39
