### ISSUE TITLE
Test: Aktiv App delegering for App som er slettet

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#783]

**Comment by jonkjetiloye** [comment]
FYI @acn-Sneha @Nyeng Vi trenger en test for scenario for dette.

Det gjelder da altså at det eksisterer aktiv app delegering for an app som tjenesteeier sletter.
Denne delegeringen skal da fortsatt vises og kunne slettes av tilgangstyrer som har delegert den

**Comment by Nyeng** [comment]
@acn-Sneha mener å huske at denne ble tatt opp i går som kandidat for manuell test, kanskje vi kan se på den sammen etterpå?

**Comment by acn-Sneha** [comment]
@Nyeng Ja, det kan vi se på

**Comment by Nyeng** [comment]
https://at24.altinn.cloud/ui/Profile?R=51555504&lm=%2Fui%2FAccessManagement%2FServicesAvailableForActor%2F%3FuserID%3D20020237%26partyID%3D50074809

Vi la til rettigheter for denne brukeren, men må vente på at appen blir slettet hos app-teamet (spurt David på Slack). Når det er gjort kan vi prøve å gjenskape

**Comment by Nyeng** [comment]
Da er denne testet ok. Setter til lukket?

- Vi startet også dialog med Apps-teamet slik at vi enklere kan få tilgang til å opprette(hvis vi ikke allerede har?) og slette apper slik at vi enklere kan teste lignende scenarier fremtiden.
