### ISSUE TITLE
Tilgangsstyrer kan ikke delegere enkeltrettigheter for app de selv har mottatt (issue 472)

### ISSUE THREAD

**Issue by ivartryti** [Altinn/altinn-access-management#832]
### Description of the bug

Dette funker for GenericAccessResource, men ikke for AltinnApps
#472

### Steps To Reproduce

1. Som avgiver, gi rollen tilgangsstyrer til en person
2. Som avgiver, Deleger en altinn app til tilgangsstyreren
3. Som tilgangsstyrer, deleger den altinn appen til en person eller org

Forventer å få status "Delegated", men får "NotDelegated". I noen tilfeller får man problemDetails respons:
```
{
  "type": "https://tools.ietf.org/html/rfc9110#section-15.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "errors": {
    "right[0].Resource": [
      "Authenticated user does not have any delegable rights for the resource: ttd/apps-test-tba"
    ]
  },
  "traceId": "00-9b4eefd77d2e0e855ef20d4385b180e7-349860b293ee442f-01"
}
```

```[tasklist]
### Test
```

**Comment by jonkjetiloye** [comment]
**Årsak:**
Bug identifisert i DelegationMetadataRepo (ny query-basert database klasse), hvor en uheldig formulert if-sjekk gjør at oppslag av App-delegeringer gitt direkte til en bruker aldri blir slått opp. Brukere med tilgang via arv av tilgang via nøkkelrolle eller hovedenhet blir ikke påvirket.

**Konsekvens:**
Denne spørringen brukes både internt ved autorisasjon av delegeringer, men også i oppslag for PIP API som PDP komponenten bruker for autorisasjon og tilgang til en App instans.

Siden database omskrivningen fra funksjoner i databasen til queries i koden ikke enda er aktivert i Prod har denne buggen hittil bare blitt eksponert i AT-miljøer og TT02.

**Comment by ivartryti** [comment]
Testet ok :)

**Comment by jonkjetiloye** [comment]
Bug også funnet i Prod ref.:
https://digdir.slack.com/archives/C079ZFURLKA/p1728476694431309

Men feilen ligger da i postgres funksjonene som bare er i bruk når UseNewQueryRepo feature er av (AT23 og Prod).

Feil utbedres ved at vi nå går live med databaseomskrivingen og aktiverer UseNewQueryRepo i alle miljøer.

**Comment by jonkjetiloye** [comment]
Dette ble hotfikset i Prod 10.10.2024 ca. kl 13:09
