### ISSUE TITLE
AppInstanceDelegation | DelegationCheck | Unexpected HttpStatus responses

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#854]
### Description of the bug

**Scenario 1:**
DelegationCheck is performed by app which is not authorized to delegate any instance access rights response.

Expected: 200 OK with empty response
Actual: 400 BadRequest

**Scenario 2:**
DelegationCheck is performed with a PlatformAccessToken issued by a platform application and not an AltinnApp.

Expected: 403 Forbidden
Actual: 400 BadRequest

### Steps To Reproduce

Se Automated Bruno requests in bug branch:
https://github.com/Altinn/altinn-access-management/tree/bug/854-AppInstanceDelegation_DelegationCheck_UnexpectedHttpStaturResponses

**Comment by sneha-sirure** [comment]
@andreasisnes Tror du har utviklet denne i bruno som jeg ser. Da kan vi lukke den tasken?
