### ISSUE TITLE
AccessTokenHandler ArgumentException on PlatformToken authorization

### ISSUE THREAD

**Issue by jonkjetiloye** [Altinn/altinn-access-management#862]
### Description of the bug

Autorisasjon av PlatformAccessToken i AccessManagement logger argument exceptions i appinsights:

https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/DataModel/%7B%22eventId%22:%22909af12a-9530-11ef-8a63-000d3a879885%22,%22timestamp%22:%222024-10-28T13:26:16.4485292Z%22%7D/ComponentId/%7B%22Name%22:%22at22-platform-ai%22,%22ResourceGroup%22:%22altinnplatform-at22-rg%22,%22SubscriptionId%22:%22de41df22-8dd0-435b-98dd-6152cd371e92%22%7D

### Steps To Reproduce

Execute a Bruno request for instance delegation for Apps. DelegationCheck e.g.:
https://github.com/Altinn/altinn-access-management/blob/main/test/Bruno/Altinn.AccessManagement/Manual%20Test%20Collection/AppsInstanceDelegation/DelegationCheck.bru

**Comment by andreasisnes** [comment]
ROOT CAUSE ANALYSIS: FML
