### ISSUE TITLE
Should local roles act as the engine for access groups?

### ISSUE THREAD

**Issue by sorensensig** [Altinn/altinn-access-management#87]
### Description

This analysis looks to decide whether today's local roles in Altinn can and/or should be used as the foundation for access groups.

This analysis is part of Epic https://github.com/Altinn/altinn-access-management/issues/82

### Analysis

- [ ] **Which problems will we inherit if we choose to use local roles as the engine rather than building a new one?** `(tech)`

> Prerequisite:
> - [ ] Not defined

> Next steps:
> - [ ] In a team meeting, if any, create a list of prerequisites for this tasks to continue.
> - [ ] In a team meeting set the next steps.

> Clarifications:
> Not defined

---

- [ ] **What should we do with the groups that have been created if we decide to roll back?** `(tech)`

> Prerequisite:
> - [ ] Not defined

> Next steps:
> - [ ] In a team meeting, if any, create a list of prerequisites for this tasks to continue.
> - [ ] In a team meeting set the next steps.

> Clarifications:
> Not defined

---

- [ ] **It must be possible to create a local role with a 3.0 service. We should have an abstraction that can cover both** `(tech)`

> Prerequisite:
> - [ ] Not defined

> Next steps:
> - [ ] In a team meeting, if any, create a list of prerequisites for this tasks to continue.
> - [ ] In a team meeting set the next steps.

> Clarifications:
> Not defined

---

**Comment by sivaglen** [comment]
Det er besluttet at lokale roller i Altinn 2 fases ut. Jeg mener derfor denne issuen ikke lenger er aktuell.

**Comment by hannekristin** [comment]
Ikke aktuell
